plugins {
    id 'com.android.library'
    id 'org.jetbrains.kotlin.android'
    id 'kotlin-kapt'
   // id "org.jetbrains.kotlin.plugin.parcelize"
}

android {
    compileSdk 33
//    引用的最低sdk不得低于我这个版本
    defaultConfig {
        namespace  "com.xcjh.base_lib"
        minSdk 21
        targetSdk 33
        versionCode 1
        versionName "1.0.1"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"



    }
    buildFeatures {
        viewBinding true
        dataBinding true
    }



}

kapt {
    arguments {
        arg("AROUTER_MODULE_NAME", project.getName())
    }
}
dependencies {
    // api "org.jetbrains.kotlin:kotlin-stdlib:1.7.20"
    api "org.jetbrains.kotlin:kotlin-stdlib:1.7.20"
   // api rootProject.ext.androidx["kotlin_core"]
    api "androidx.appcompat:appcompat:1.5.1"

    api "com.google.android.material:material:1.7.0"
    api "junit:junit:4.13.2"
    api "androidx.test.ext:junit:1.1.5"
    api "androidx.test.espresso:espresso-core:3.5.1"
    // viewModel
    api "androidx.activity:activity-ktx:1.6.1"
    api "androidx.fragment:fragment-ktx:1.5.5"
    api "androidx.lifecycle:lifecycle-viewmodel-ktx:2.5.1"
    api "androidx.lifecycle:lifecycle-livedata-ktx:2.5.1"



    /*==============================三方工具库==========================*/
    //模块启动初始化Application
    implementation Libs.androidx_startup
    //glide图片加载库
    //  api rootProject.ext.dependencies["glide"]
    api 'com.github.bumptech.glide:glide:4.16.0'
    //引入Glide的注解处理器（Annotation Processor）的。Glide的注解处理器用于在编译时生成GlideApp类
    kapt 'com.github.bumptech.glide:compiler:4.15.1'

    //阴影控件
    api "com.github.lihangleo2:ShadowLayout:3.3.2"
    //适配
    api "me.jessyan:autosize:1.2.1"
    //沉浸式
    api "com.geyifeng.immersionbar:immersionbar:3.2.2"
    api "com.geyifeng.immersionbar:immersionbar-ktx:3.2.2"
    //BaseRecyclerViewAdapterHelper
    api "io.github.cymchad:BaseRecyclerViewAdapterHelper:3.0.14"

    //******==================网络=================
    api "com.squareup.retrofit2:converter-gson:2.9.0"
//    api "com.github.Justson.AgentWeb:agentweb-core:v5.0.0-alpha.1-androidx"
    api 'io.github.justson:agentweb-core:v5.1.1-androidx'
    //动态替换BaseUrl库 使用可参考 https://github.com/JessYanCoding/RetrofitUrlManager
    api 'me.jessyan:retrofit-url-manager:1.4.0'
    // Gson 解析容错：https://github.com/getActivity/GsonFactory
//    api 'com.github.getActivity:GsonFactory:6.3'
    api 'com.github.getActivity:GsonFactory:9.6'
    // Json 解析框架：https://github.com/google/gson
    api 'com.google.code.gson:gson:2.10.1'
    api 'com.kunminx.arch:unpeek-livedata:7.8.0'
    //ws
    api "org.java-websocket:Java-WebSocket:1.5.3"
    api 'com.github.getActivity:XXPermissions:18.63'
    //指示器库
    api 'com.github.hackware1993:MagicIndicator:1.7.0'
    api 'com.github.liangjingkanji:BRV:1.5.8'

}