workflow:
  rules:
    # 排除 -latest 结尾的 tag，防止 Releaser token 创建 tag 后触发权限错误
    - if: $CI_COMMIT_TAG =~ /-latest$/
      when: never
    - when: always

include:
  - component: gitlab.iptco.me/big/gitlab-ci/android-app@main
    inputs:
      deploy_name:  "tio"
      runner_type: "shell"
      runner_tag: "ios"
      branch_build_type_map: "dev:debug,test:qatest,pre-production:release"
      auto_package_branches: "^(test|pre-production)$"

before_script:
  - echo "user.uid=$USER_UID" >> local.properties
  - echo "user.token=$USER_TOKEN" >> local.properties