include:
  - component: gitlab.iptco.me/big/gitlab-ci/android-app@main
    inputs:
      deploy_name:  "tio"
      runner_type: "docker"
      runner_tag: "ios"
      branch_build_type_map: "dev:debug,test:qatest,pre-production:release"
      auto_package_branches: "^(test|pre-production)$"

before_script:
  - echo "user.uid=$USER_UID" >> local.properties
  - echo "user.token=$USER_TOKEN" >> local.properties