apply plugin: 'com.google.devtools.ksp'

logger.warn "_koin.gradle applied in module: ${project.path}, ext.koinApplied:${ext.has("koinApplied")}"  // 如 :app、:featureA
if (ext.has("koinApplied")) {
    return
}
ext.koinApplied = true

project.afterEvaluate {
    ksp {
        arg("KOIN_GENERATED_PACKAGE", project.extensions.getByName("android").namespace)
    }
}

dependencies {
    /*// Koin Annotations
    implementation("io.insert-koin:koin-annotations:1.3.0")
    // Koin Annotations KSP Compiler
    ksp("io.insert-koin:koin-ksp-compiler:1.3.0")*/
    implementation(project(":plugin_koin"))
    ksp(project(":plugin_koin"))
}