def localProps = new Properties()
def localPropsFile = rootProject.file("local.properties")
if (localPropsFile.exists()) {
    localPropsFile.withInputStream { localProps.load(it) }
}

def qatestDebuggable = localProps.getProperty("qatest.debuggable", "false")
        .trim()
        .toBoolean()

android {
    signingConfigs {
        debug {
            storeFile rootProject.file("./signkey/wls.jks")
            storePassword 'WLS_ANDROID_$20250325$_V0xTX0FORFJPSURfU1RPUkVfUEFTU1dPUkQ='
            keyAlias 'wls'
            keyPassword 'WLS_ANDROID_$20250325$_V0xTX0FORFJPSURfS0VZX1BBU1NXT1JE'
            v1SigningEnabled true
            v2SigningEnabled true
        }

        //测试专用
        qatest {
            storeFile rootProject.file("./signkey/wls.jks")
            storePassword 'WLS_ANDROID_$20250325$_V0xTX0FORFJPSURfU1RPUkVfUEFTU1dPUkQ='
            keyAlias 'wls'
            keyPassword 'WLS_ANDROID_$20250325$_V0xTX0FORFJPSURfS0VZX1BBU1NXT1JE'
            v1SigningEnabled true
            v2SigningEnabled true
        }

        release {
            storeFile rootProject.file("./signkey/wls.jks")
            storePassword 'WLS_ANDROID_$20250325$_V0xTX0FORFJPSURfU1RPUkVfUEFTU1dPUkQ='
            keyAlias 'wls'
            keyPassword 'WLS_ANDROID_$20250325$_V0xTX0FORFJPSURfS0VZX1BBU1NXT1JE'
            v1SigningEnabled true
            v2SigningEnabled true
        }
    }

    buildTypes {
        debug {
            zipAlignEnabled true
            minifyEnabled false
            debuggable true
            jniDebuggable true
            signingConfig signingConfigs.debug
        }

        //测试专用
        qatest {
            debuggable qatestDebuggable
            zipAlignEnabled true
            minifyEnabled false
            signingConfig signingConfigs.qatest
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), rootProject.file('app/proguard-rules.pro')
        }

        release {
            zipAlignEnabled true
            minifyEnabled false
            shrinkResources false
            debuggable false
            signingConfig signingConfigs.release
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), rootProject.file('app/proguard-rules.pro')
        }

    }
}