[versions]
agp = "8.1.1"
coreSplashscreen = "1.0.1"
gson = "2.10.1"
jsbridge = "1.0.4"
kotlin = "1.9.0"
coreKtx = "1.9.0"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
appcompat = "1.7.0"
material = "1.12.0"
lifecycleRuntimeKtx = "2.8.7"
activityCompose = "1.10.1"
composeBom = "2024.04.01"
activity = "1.9.0"
constraintlayout = "2.2.1"
ijkPlayerVersion ="0.8.8"
annotationJvm = "1.9.1"
media3Exoplayer = "1.5.1"
exoPlayer="r1.5.11"
core = "1.9.0"
drawerlayout = "1.2.0"
koin = "3.5.0"
okhttps = "4.12.0"
protobuf = "4.30.1"
mmkv = "2.0.2"
room = "2.6.1"
junitKtx = "1.2.1"
runner = "1.6.2"
navigation = "2.8.9"
annotation = "1.9.1"
lifecycleLivedataKtx = "2.8.7"
lifecycleViewmodelKtx = "2.8.7"
window = "1.3.0"
glide = "4.16.0"
autoSize = "1.2.1"
ksp = "1.9.0-1.0.13"

immersionbar = "3.2.2"
legacySupportV4 = "1.0.0"
fragmentKtx = "1.5.6"
startupRuntime = "1.2.0"
[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "coreSplashscreen" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
jsbridge = { module = "com.github.lzyzsd:jsbridge", version.ref = "jsbridge" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
ijkplayer = { group = "tv.danmaku.ijk.media", name = "ijkplayer-java", version.ref = "ijkPlayerVersion" }
androidx-annotation-jvm = { group = "androidx.annotation", name = "annotation-jvm", version.ref = "annotationJvm" }
android-exoplayer = { group = "com.google.android.exoplayer", name = "exoplayer", version.ref = "exoPlayer" }
androidx-core = { group = "androidx.core", name = "core", version.ref = "core" }
androidx-drawerlayout = { group = "androidx.drawerlayout", name = "drawerlayout", version.ref = "drawerlayout" }
koin = { group = "io.insert-koin", name = "koin-android", version.ref = "koin" }
mmkv = { module = "com.tencent:mmkv", version.ref = "mmkv" }
startup = { group = "androidx.startup", name = "startup-runtime", version = "1.1.1" }
okhttps = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttps" }
protobuf = { group ="com.google.protobuf", name = "protobuf-javalite", version.ref = "protobuf" }
navigation-fragment = { group = "androidx.navigation", name = "navigation-fragment", version.ref = "navigation" }
navigation-ui = { group = "androidx.navigation", name = "navigation-ui", version.ref = "navigation" }
navigation-fragment-ktx = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "navigation" }
navigation-ui-ktx = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "navigation" }
navigation-dynamic-features-fragment = { group = "androidx.navigation", name = "navigation-dynamic-features-fragment", version.ref = "navigation" }
room = { group = "androidx.room", name = "room-runtime", version.ref = "room" }
room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room" }
androidx-junit-ktx = { group = "androidx.test.ext", name = "junit-ktx", version.ref = "junitKtx" }
androidx-runner = { group = "androidx.test", name = "runner", version.ref = "runner" }
androidx-annotation = { group = "androidx.annotation", name = "annotation", version.ref = "annotation" }
androidx-lifecycle-livedata-ktx = { group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version.ref = "lifecycleLivedataKtx" }
androidx-lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycleViewmodelKtx" }
androidx-window = { group = "androidx.window", name = "window", version.ref = "window" }
immersionbar = { group = "com.geyifeng.immersionbar", name = "immersionbar", version.ref = "immersionbar" }
glide = { group = "com.github.bumptech.glide", name = "glide", version.ref = "glide" }
glidecompiler = { group = "com.github.bumptech.glide", name = "compiler", version.ref = "glide" }
autosize = {group = "me.jessyan", name = "autosize", version.ref = "autoSize"}

androidx-legacy-support-v4 = { group = "androidx.legacy", name = "legacy-support-v4", version.ref = "legacySupportV4" }
androidx-fragment-ktx = { group = "androidx.fragment", name = "fragment-ktx", version.ref = "fragmentKtx" }
androidx-startup-runtime = { group = "androidx.startup", name = "startup-runtime", version.ref = "startupRuntime" }
[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "agp" }
navigation-safeargs = { id = "androidx.navigation.safeargs.kotlin", version.ref = "navigation" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
