plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.android'
    id 'kotlin-kapt'
}
apply from: rootProject.file("gradle/flavor.gradle")
apply from: rootProject.file("gradle/gamesdk_deps.gradle")

android {
    namespace 'com.example.myapplication'
    compileSdk 33

    defaultConfig {
        applicationId "com.example.test"
        minSdk 21
        targetSdk 33
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"

        def prop = new Properties()
        prop.load(project.rootProject.file("local.properties").newDataInputStream())
        buildConfigField "String", "token", prop.getProperty("user.token").with { delegate ? "\"${delegate}\"": "\"\"" }
    }

    sourceSets {
        main {
            jniLibs.srcDirs = ['jniLibs']
        }
    }
    buildFeatures {
        viewBinding true
        dataBinding true
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    kotlinOptions {
        jvmTarget = '1.8'
    }

    applicationVariants.configureEach {
        variant ->
        variant.outputs.configureEach {
            def date = String.format('%s', new Date().format('yyyyMMddHHmmss'))
            def gitVersion = getGitVersion()
            outputFileName = "gamesdk-${variant.name}-v${variant.versionName}-${variant.versionCode}-${date}-${gitVersion}.apk"
        }
    }
}


dependencies {
    //implementation fileTree(dir: 'libs', include: ['*.jar', '*.aar'])
//    implementation 'androidx.core:core-ktx:1.8.0'
    implementation "com.github.getActivity:XXPermissions:16.8"
    implementation 'androidx.appcompat:appcompat:1.6.1'
//    implementation 'com.google.android.material:material:1.5.0'
    implementation 'com.google.android.material:material:1.4.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.1.5'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.5.1'
    implementation project(path: ':game_sdk_new')
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
//    implementation 'com.github.r21nomi:glrippleview:1.0.0'

    //outerTestImplementation 'com.squareup.leakcanary:leakcanary-android:2.14'
   // innerTestImplementation 'com.squareup.leakcanary:leakcanary-android:2.14'
    debugImplementation 'com.squareup.leakcanary:leakcanary-android:2.14'

//    implementation  'io.github.scwang90:refresh-layout-kernel:2.0.5'      //核心必须依赖
//    implementation  'io.github.scwang90:refresh-header-classics:2.0.5'    //经典刷新头
//    implementation  'io.github.scwang90:refresh-footer-classics:2.0.5'    //经典加载
}

