syntax = "proto3";
// 因仅需要解析，可以用 pb3 解析 pb2 生成的数据

package game.common.proto;

// client -> server 方向的消息

// 0-1: 回复 server 的心跳
// 0-2: client 主动发出的心跳

// 7-7: 登录游戏服
message LoginReq {
    string agent_name = 1;
    string token = 2; // 登录token。client从大厅/商户登录获取
    string version = 3; // client 版本

    string base = 4; // 热更版本。仅供 cocos 连 logon 使用，其他不用传
    string game_version = 5; // 小游戏版本。仅供 cocos 连 logon 使用，其他不用传

    int32 platform = 6; // 账号平台 2=2n1（默认）、4=试玩、5=h5。cocos 可不传
    int32 server = 7; // serverID。游戏服合并端口后，cocos 用此字段识别进哪个服
    int32 requestId = 8; // 用于识别重复请求的唯一id。仅供 cocos 识别登录重发使用，h5 不用传
    string nickname = 9; // 暱稱
}

// 8-7: 进房间/坐下（无携带消息，slot类有特殊的消息）

// 8-10: 离开游戏（无携带消息）

// 500-999: 客户端回传数据。纯回传，server 无业务处理，无返回
message PingBackReq {
    string data = 1; // 纯文本数据
}

