plugins {
    id 'com.android.library'
    id 'org.jetbrains.kotlin.android'
    id 'maven-publish'
}

android {
    namespace 'com.cn.game.sdk'
    compileSdk 33

    defaultConfig {
        minSdk 21
        targetSdk 33
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        consumerProguardFiles "consumer-rules.pro"
        ndk {
            // 只接入 armeabi-v7a 和 x86 架构
            //abiFilters 'armeabi-v7a', 'x86', 'arm64-v8a', 'x86_64'
            abiFilters 'armeabi-v7a', 'arm64-v8a'
        }
        externalNativeBuild{
            cmake {
                //cppFlags "-Isrc/main/cpp"
                cppFlags '-std=c++11'
            }
        }

    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'

        }
    }
    libraryVariants.all { variant ->
        if (variant.buildType.name == 'release') {
            variant.outputs.all { output ->
                outputFileName = "game_sdk-release.aar"
            }
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    kotlinOptions {
        jvmTarget = '1.8'
    }
    externalNativeBuild {
        cmake {
            path file('src/main/cpp/CMakeLists.txt')
            version '3.18.1'
        }
    }
}
//// 配置发布
//publishing {
//    publications {
//        myLibrary(MavenPublication) {
//            groupId = 'com.cn.game'
//            artifactId = 'game_sdk'
//            version = '1.0.0'
//            artifact("$buildDir/outputs/aar/game_sdk-release.aar")
//        }
//    }
//}
//publishing {
//    publications {
//        myLibrary(MavenPublication) {
//            groupId = 'com.cn.game'
//            artifactId = 'game_sdk'
//            version = '1.0.0'
//
//            // 将 afterEvaluate 块移动到 publications 块内部
//            afterEvaluate {
//                logger.lifecycle("Executing afterEvaluate block for publishing...")
//
//                // 获取 release variant
//                def releaseVariant = android.libraryVariants.find { it.name == 'release' }
//                if (releaseVariant == null) {
//                    logger.error("Release variant not found!")
//                    return
//                }
//                logger.lifecycle("Found release variant: ${releaseVariant.name}")
//
//                // 获取 variant 的输出
//                def output = null
//                releaseVariant.outputs.each { variantOutput ->
//                    if (variantOutput.outputFile != null) {
//                        output = variantOutput.outputFile
//                        return
//                    }
//                }
//                if (output == null) {
//                    logger.error("Output file not found for release variant!")
//                    return
//                }
//                logger.lifecycle("Found output file: ${output}")
//
//                // 配置发布的 artifact 名称和构建任务
//                artifact(output) {
//                    builtBy("assembleRelease")
//                    classifier releaseVariant.name
//                }
//            }
//        }
//    }
//}
//// 将发布任务依赖添加到assemble任务中
//tasks.named('assemble').configure {
//    dependsOn 'publish'
//}


dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar', '*.aar'])
//    implementation 'androidx.core:core-ktx:1.8.0'
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.google.android.material:material:1.4.0'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
//    testImplementation 'junit:junit:4.13.2'
//    androidTestImplementation 'androidx.test.ext:junit:1.1.5'
//    androidTestImplementation 'androidx.test.espresso:espresso-core:3.5.1'
    //组件依赖基础库
    implementation project(':base_lib')
    implementation 'com.github.liangjingkanji:Engine:0.0.74' // 快速开发基础库
}