syntax="proto3";
package game.mod.proc.yf.proto.req;

// 各种单位:
// 机率 1=0.0001, ex: 1234 = 12.34%
// 金钱 1=0.01, ex: 123 = 1.23元
// 赔率 1=1, ex: 1.2 = 1.2倍
// 时间 1=1ms, ex: 12400 = 12.4 s = 12400 ms

// 下注
message BetReq {
  // 小游戏 id
  int32 miniGameId = 1;
  // 下注资料
  repeated AreaBet areaBet = 2;
}

// 每个注区的押注资料
message AreaBet {
  // 注区ID:
  int32 areaId = 1;
  // 玩家注区总下注金额
  int32 betScore = 2;
}

//---------- 投注与开奖纪录相关 ----------//
// 查询投注记录
message ListBetDetailLogReq {
  int32 miniGameId = 1;
  int32 status = 2; // [0=全部, 1=已中奖, 2=未中奖], 未成立的單不列入投注記錄
  int32 yyyy = 3; // 查询日期-年
  int32 mm = 4; // 查询日期-月
  int32 dd = 5; // 查询日期-日

  int64 beginDataId = 6; // 从哪个Id往前找, singular, 0=最新的区段, ex: beginDataId = 100, 找 [99...90]
}

// 查询开奖纪录
message ListRoundInfo {
  int32 miniGameId = 1;
  int64 beginDataId = 2; // 从哪个索引往前找, singular, 0=最新的区段
}

// 视野
message Group {
  string id = 1; // group id
  string data = 2; // 透传资料（转抛）
}

//---------- 测试用相关 ----------//
// 盘面指定
message TestAssign {
  // 小游戏 id
  int32 miniGameId = 1;
  // 牌面
  repeated int32 elements = 2;
}
