syntax="proto3";
package game.mod.proc.yf.proto.res;

//---------- 登入相关 ----------//
// 登入后给玩家资料
message UserData {
  int64 userId = 1; // 用户id
  int64 score = 2; // 身上的钱
}

//---------- 进房后相关 ----------//
// 进房后给, 房间资讯
message RoomInfo {
  // 当前所处阶段：1.下注 2.结算
  int32 stage = 1;
  // 当前阶段剩余时间倒计时(ms)
  int32 countDown = 2;
  // 小游戏资讯
  repeated MiniGameInfo miniGameInfoList = 3;
  // 我的未开奖投注资讯(所有miniGame, 给介面上此期未开奖)
  repeated BetBriefInfo uncheckedBetBriefInfoList = 4;
  // 玩家资料
  UserData self = 5; // 暂时放置 EnterRoom，以后会再移走。
  // 小游戏显示顺序
  repeated int32 miniGameShowOrder = 6;
  // 玩家登入时间
  int64 userLoginTime = 7;
}

// 小游戏资讯
message MiniGameInfo {
  // 小游戏 id
  int32 id = 1;
  // 注区资讯
  repeated AreaInfo areaInfoList = 2;
  // 当前期号
  string roundId = 3;
  // 开奖纪录(若进场时为结算阶段, 则包含此局结果)
  Trend trend = 4;
}

// 注区资讯
message AreaInfo {
  int32 id = 1; // 注区ID
  string name = 2; // 注区名称
  int32 type = 3; // 注区类别
  string typeName = 4; // 注区类别名称
  float odds = 5; // 赔率
  int32 minLimit = 6; // 投注下限
  int32 maxLimit = 7; // 投注上限
}

// 开奖资讯（通用格式定义，能符合未来新游戏的扩充）
message RoundInfo {
  // 资料索引
  int64 dataId = 1;
  // 期号
  string roundId = 2;
  // 牌面种类
  int32 elementType = 3; // 1:扑克牌, 2:麻将牌, 3:天九牌, 4:骰子...
  // 表演资讯
  repeated ActorPerform performs = 4;
  // 获胜注区列表：(内容数值定义：注区ID)
  repeated int32 winAreaIds = 5;
}

message ActorPerform {
  // 牌面
  repeated int32 elements = 1; // (根据elementType决定)
  // 牌型
  repeated int32 patterns = 2; // (根据miniGameId决定) 牛牛, 铁支
  // 结果
  repeated int32 performResult = 3; // (通用) 0:undefined, 1:胜, 2:败, 3:和
}

// 开奖历史
message Trend {
  repeated RoundInfo roundInfoList = 1;
}

// 开始新的一轮
message BeginNewRound {
  // 当前阶段剩余时间倒计时(ms)
  int32 countDown = 1;
  // 期号
  string roundId = 2;
}

// 投注资讯
message BetInfo {
  // 注区ID
  int32 areaId = 1;
  // 注区总下注金额
  int64 betScore = 2;
}

// 下注结果
message MyMiniGameBetResult{
  // 小游戏 id
  int32 miniGameId = 1;
  // 押注资讯
  repeated BetResultInfo betResultInfoList = 2;
  // 当前玩家剩余金币
  //int64 score = 3;
}

message BetResultInfo {
  BetInfo betInfo = 1;
  int32 result = 2;// OrderStatus
}

// 广播其他同房玩家下注资讯(不含自己)
message UserBetBriefInfo {
  // 玩家id
  int64 userId = 1;
  // 玩家暱称
  string userNickName = 2;
  // 押注资讯
  BetBriefInfo betBriefInfo = 3;
}

message BetBriefInfo{
  // 小游戏 id
  int32 miniGameId = 1;
  // 押注资讯
  repeated BetInfo betInfoList = 2;
}

// 各小游结算
message BeginSettle {
  // 当前阶段剩余时间倒计时(ms)
  int32 countDown = 1;
  // 各小游戏开奖结果
  repeated MiniGameSettle miniGameSettles = 2;
  // 各小游戏结算结果
  repeated ListBetDetailLog gameBetDetailLogs = 3;
  // 最终身上金额
//  int64 score = 4;
}

// 单一小游戏结算, 进入settle就会传开奖结果, 但开奖结果与新的投注记录须等settle倒数结束才可以呈现到画面
message MiniGameSettle {
  // 小游戏 id
  int32 miniGameId = 1;
  // 开奖资讯
  RoundInfo roundInfo = 2;
  // 此局结算后新增的投注纪录
  repeated BetDetailLog betLogs = 3;
}

// 查询最近有下注的n期详细投注记录
message GameLatestBettingRoundDetailLog{
  repeated ListBetDetailLog gameLogs = 1;
}

// 广播其同房玩家中奖资讯(含自己), 这一局的所有单总和，有赢就发
message RoomUserWinScoreInfo {
  repeated UserWinScoreInfo userWinInfoList = 1;
}

message UserWinScoreInfo {
  int64 userId = 1; // 玩家id
  string userNickName = 2; // 玩家暱称
  int32 miniGameId = 3; // 玩家中奖游戏
  int64 winScore = 4; // 中奖金额
}

// 选择性刷新玩家属性
message RefreshUserProperties {
  optional string groupId = 1;
  optional int64 score = 2;
}

//---------- 投注与开奖纪录相关 ----------//
message ListBetDetailLog {
  int32 miniGameId = 1;
  repeated BetDetailLog betDetailLogs = 2;
}

// 每一单的投注记录, 未成立的单不列入
message BetDetailLog {
  // 资料索引序号
  int64 dataId = 1;
  // 期号
  string roundId = 2;
  // 注区
  int32 areaId = 3;
  // 投注金额
  int64 betScore = 4;
  // 中奖金额(没中奖为0)
  int64 deltaScore = 5;
  // 投注时间
  int64 betTime = 6;
}

message ListTrend {
  int32 miniGameId = 1;
  repeated RoundInfo infoList = 2;
}