package game.chat.proto;

import "google/protobuf/timestamp.proto";
import "game-chat-common.proto";

// 登录请求：90-1101
message LoginReq {
  required int64 uid = 1;
  required string token = 2;
  required ChatType chatType = 3; // 链接类型枚举
}

// 链接类型枚举
enum ChatType {
  LOBBY = 1; // 大厅
  GAME = 2;  // 游戏
}

// 登录响应：90-1102
message LoginResp {
  required int32 code = 1;      // 0-成功，1-失败原因
  optional string message = 2;  // 失败原因提示
  optional int64 uid = 3;       // 成功时返回用户ID
  optional string username = 4; // 成功时返回用户名
  optional int32 avatarId = 5;  // 成功时返回用户头像
}

// 错误代码枚举
enum ErrorCode {
  SUCCESS = 0;                      // 成功
  INVALID_MESSAGE = 1;              // 无效消息
  ROOM_NOT_FOUND = 2;               // 未找到房间
  USER_NOT_IN_ROOM = 3;             // 用户不在房间
  MESSAGE_RATE_LIMITED = 6;         // 用户发言限制
  ACCOUNT_LOGGED_IN_ELSEWHERE = 8;  // 异地登陆，登出通知
  CHECK_BET_AMOUNT = 9;             // 用户有效投注额不足
  CHECK_LATEST_SCORE = 11;          // 用户余额不足
  // 添加其他错误码...
}

// 客户端 -> 服务器

// 1. 进入聊天室：500-1001
message EnterChatRoomReq {
  required uint64 roomId = 1;             // 房间ID
  required ChatType chatType = 2;   // 链接类型枚举
}
// 响应：500-1002
message EnterChatRoomResp {
  required int32 code = 1;
  optional uint64 chatroomId = 2;   // 可选，聊天室唯一标识
}

// 2. 离开聊天室：500-1003
message LeaveChatRoomReq {
  required uint64 roomId = 1;             // 房间ID
  required ChatType chatType = 2;   // 链接类型枚举
}
// 响应：500-1004
message LeaveChatRoomResp {
  required int32 code = 1;        // 状态码
}

// 3. 发送消息：500-1005
message SendMsgReq {
  required uint64 roomId = 1;             // 房间ID
  required string content = 2;            // 消息内容
  repeated uint64 refUid = 3;             // @用户 ID
  required ChatType chatType = 4;   // 链接类型枚举
  required MsgType msgType = 5;           // 消息类型
  map<string, string> extraData = 6;      // 额外数据 如分享链接等
}

// 占位符类型
// @用户：[**]
// 分享：[***]
// 表情：/id=xx/
// 大图：/bid=xx/


enum MsgType {
  MSG_TYPE_SYSTEM = 0;  // 系统消息 - 仅限后台发送
  MSG_TYPE_TEXT = 1;    // 文字消息
  MSG_TYPE_SHARE = 2;   // 分享消息
}

// 响应：500-1006
message SendMsgResp {
  required int32 code = 1;          // 状态码
  optional string errorMessage = 2; // 多语言的错误提示信息
}

// 4. 获取聊天记录：500-1007
message GetChatHistoryReq {
  required uint64 roomId = 1;     // 房间ID
  required int32 page = 2;        // 页码
  required int32 pageSize = 3;    // 分页大小,默认20
  optional string requestId = 4;  // 请求唯一标识符
}
// 响应：：500-1008
message GetChatHistoryResp {
  required int32 code = 1;          // 状态码
  repeated ChatMsg msgs = 2;        // 聊天记录
  required int32 totalPages = 3;    // 聊天记录
  required int32 totalRecords = 4;  // 总页数
  optional string requestId = 5;    // 与请求中的 requestId 对应
}

message ChatMsg {
  required uint64 uid = 1;                          // 用户ID
  required string userName = 2;                     // 用户名称
  required int32 avatarId = 3;                      // 用户头像
  optional uint64 msgId = 4;                        // 消息ID
  required string content = 5;                      // 消息内容
  optional google.protobuf.Timestamp timestamp = 6; // 消息时间戳
  repeated uint64 refUids = 7;                       // @用户ID
  map<uint64, RefUser> refInfos = 8;                 // @用户信息

  optional int32 onlyForSelf = 10;                  // 1-仅自己可见 0-所有人可见. 理论上不需要客户端 发这个字段
  optional string replaceUserName = 11;             // 脱敏用户名

  required MsgType msgType = 13;                    // 消息类型
  map<string, string> extraData = 14;               // 额外数据 如分享链接等

  optional ChatType chatType = 15;                  // 链接类型枚举
}

// 5. 获取用户统计信息：500-1009
message GetUserStatisticReq {
  required uint64 uid = 1;                // 用户头像
}
// 响应：500-1010
message GetUserStatisticResp {
  required int32 code = 1;          // 状态码
  required int64 roundCount = 2;    // 投注测试
  required int64 validBetScore = 3; // 有效投注
}

// 6. 设置用户头像：500-1011
message SetUserAvatarReq {
  required int32 avatarId = 1;  // 用户头像
}
// 响应：500-1012
message SetUserAvatarResp {
  required int32 code = 1;  // 状态码
}

// 7. 更新用户信息：500-1013
message SyncUserNameReq {
}
// 响应 500-1014
message SyncUserNameResp {
  required int32 code = 1;  // 状态码
}

// 8. 校验校验投注额：500-1015
message CheckScoreReq {
}
// 响应：500-1016
message CheckScoreResp {
  required int32 code = 1;          // 状态码
  optional int64 score = 2;         // 最低要求金额
  optional string errorMessage = 3; // 多语言的错误提示信息
}

//9. 举报请求：500-1017
message ReportUserReq {
  required uint64 uid = 1;                // 用户ID
  required ChatType chatType = 2;   // 链接类型枚举
  required int32 type = 3;                // 举报类型 1.色情低俗 2.非法广告 3.辱骂他人 4.违法违规 5.涉嫌诈骗 6.其他
}
// 举报响应：500-1018
message ReportUserResp{
  required int32 code = 1;  // 状态码
}

// 服务器 -> 客户端
// 1. 消息通知
message MsgNotify {
  required uint64 roomId = 1; // 房间ID
  optional ChatMsg msg = 2;   // 最新的聊天数据
}
// 2. 系统通知 500-2003
message SysMsgNotify{
  required NotificationType type = 1;   // 通知类型
  map<string, string> payload = 2;      // 扩展字段（用于不同类型的数据补充）==> 详见“扩展字段”
}
// 通知类型
enum NotificationType {
  NOTIFICATION_TYPE_UNSPECIFIED = 0;
  USER_BANNED = 1;          // 用户封禁
  MERCHANT_BANNED = 2;      // 商户封禁
  USERNAME_SENSITIVE = 3;   // 用户名涉及敏感词
  USERNAME_NORMAL = 4;      // 用户名正常
  USER_REPORT = 5;          // 用户被举报
  USER_BANNED_NOTIFY = 6;   // 封禁用户通知
}

// 扩展字段
// userId --------------------------- 用户ID
// chatType ------------------------- 链接类型枚举
// replace_user_name ---------------- 脱敏用户名/恢复正常的用户名
// report_type ---------------------- 举报类型
// report_count --------------------- 未被处理的举报次数(不同用户)
// mute_count ----------------------- 封禁次数
// next_day ------------------------- 下次封禁天数 -1:永久
// mute_until ----------------------- 封禁截止时间(毫秒时间戳)