plugins {
    id 'com.android.library'
    id 'org.jetbrains.kotlin.android'
    id 'maven-publish'
    id 'com.google.protobuf'
    id("kotlin-kapt")
}
apply from: "${rootDir.path}/gradle/pin.gradle"
apply from: rootProject.file("gradle/flavor.gradle")

android {
    namespace 'com.cn.game.sdk2'
    compileSdk 33

    defaultConfig {
        minSdk 21
        targetSdk 33
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        consumerProguardFiles "consumer-rules.pro"
        ndk {
            // 只接入 armeabi-v7a 和 x86 架构
            //abiFilters 'armeabi-v7a', 'x86', 'arm64-v8a', 'x86_64'
            abiFilters 'armeabi-v7a', 'arm64-v8a'
        }
        externalNativeBuild {
            cmake {
                //cppFlags "-Isrc/main/cpp"
                cppFlags '-std=c++11'
            }
        }

    }

    buildTypes {
        release {
//            zipAlignEnabled true
//            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'

        }
        debug {
            zipAlignEnabled true
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
            jniDebuggable true
        }
    }
    libraryVariants.all { variant ->
        variant.outputs.all { output ->
            def date = String.format('%s', new Date().format('yyyyMMddHHmmss'))
            def gitVersion = getGitVersion()
            outputFileName = "gamesdk-${variant.name}-${date}-${gitVersion}.aar"
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    buildFeatures {
        viewBinding true
        dataBinding true
    }
    kotlinOptions {
        jvmTarget = '1.8'
    }
    externalNativeBuild {
        cmake {
            path file('src/main/cpp/CMakeLists.txt')
            version '3.18.1'
        }
    }

    sourceSets {
        main {
            proto {
                srcDir 'src/main/protos'
            }
        }
    }
    protobuf {
        protoc {
            artifact = 'com.google.protobuf:protoc:3.19.2'
        }
        generateProtoTasks {
            all().each { task ->
                task.builtins {
                    remove java
                }
                task.builtins {
                    java {}// 生产java源码
                }
            }
        }
    }
}

dependencies {
    //implementation fileTree(dir: 'libs', include: ['*.jar', '*.aar'])
    implementation "androidx.appcompat:appcompat:1.6.1"
    implementation "com.google.android.material:material:1.5.0"
    implementation "androidx.lifecycle:lifecycle-runtime-ktx:2.5.1"
    implementation "androidx.lifecycle:lifecycle-viewmodel-ktx:2.5.1"
    implementation "androidx.startup:startup-runtime:1.1.1"

    //组件依赖基础库
    implementation 'com.google.protobuf:protobuf-java:3.19.1'
    implementation('com.github.li-xiaojun:XPopup:2.10.0') {
        exclude group: "com.davemorrissey.labs", module: "subsampling-scale-image-view-androidx"
    }
    implementation 'com.airbnb.android:lottie:6.4.0'
    implementation "me.jessyan:autosize:1.2.1"
    api "com.geyifeng.immersionbar:immersionbar:3.2.2"
    api "com.geyifeng.immersionbar:immersionbar-ktx:3.2.2"
    implementation 'com.kunminx.arch:unpeek-livedata:7.8.0'
    implementation "org.java-websocket:Java-WebSocket:1.5.3"
    implementation 'com.github.hackware1993:MagicIndicator:1.7.0'
    implementation 'com.github.liangjingkanji:BRV:1.5.8'

    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.1.5'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.5.1'
}

/****************************************************/
/*publishing {
    publications {
        // 发布 AAR 文件
        maven(MavenPublication) {
            // 设置发布的坐标信息
            groupId 'com.example'
            artifactId 'my-library'
            version '1.0.0'

            // 发布的文件
            artifact("$buildDir/my-library-release.aar")

            // 包含源代码
            artifact("$buildDir/my-library-release-sources.jar") {
                classifier 'sources'
            }
        }
    }
}
// 复制 AAR 文件和源代码到指定目录
task copyToHello(type: Copy) {
    from("$buildDir/outputs/aar/") {
        include '*.aar'
        include '*.jar'
    }
    into("$rootDir/hello")
}
tasks.named('publish') {
    dependsOn 'copyToHello'
}*/

/****************** publish *************************/
def GroupId = 'com.cn.game.sdk2'
def ArtifactId = 'game'
def Version = "1.0.0-SNAPSHOT"

def userName = "admin"
def passWord = "luxury@888!"


def releasesRepoUrl = "file:///${System.getenv("HOME")}//.m2/repository"
//def releasesRepoUrl = "http://172.16.10.13/repository/maven-snapshots/"
tasks.register('generateSourcesJar', Jar) {
    from android.sourceSets.main.java.srcDirs
    archiveClassifier.set("sources")
}
afterEvaluate {
    publishing {
        //发布的 arr 包配置
        publications {
            //名字可以自己指定，如果有多渠道，整段多复制一个
            release(MavenPublication) {
                groupId = GroupId//公司域名
                artifactId = ArtifactId//该aar包的名称
                version = Version//版本号


                // 必须有这个 否则不会上传AAR包
                afterEvaluate { artifact(tasks.getByName("bundleReleaseAar")) }
                // 多渠道，可以自行指定aar路径
                // def projectName = project.getName()
                // artifact "build/outputs/aar/${projectName}-release.aar"
                // 上传source，这样使用方可以看到方法注释
                artifact generateSourcesJar
                //依赖关系
                pom.withXml {
                    def dependenciesNode = asNode().appendNode("dependencies")
                    configurations.implementation.allDependencies.forEach() { Dependency dependency ->
                        if (dependency.version != "unspecified" && dependency.name != "unspecified") {
                            def dependencyNode = dependenciesNode.appendNode('dependency')
                            dependencyNode.appendNode('groupId', dependency.group)
                            dependencyNode.appendNode('artifactId', dependency.name)
                            dependencyNode.appendNode('version', dependency.version)
                        }
                    }
                }
            }
        }

        //仓库地址配置
        repositories {
            maven {
                //允许使用 http
                //allowInsecureProtocol = true
                url = releasesRepoUrl
                /*credentials {
                    username = userName
                    password = passWord
                }*/
            }
        }
    }
}

